[Metadata]
 Name                             = AuroraBar
 Version                          = 2.1.5b
 Author                           = deflore08 (deflore08@gmail.com) | https://www.deviantart.com/deflore08
 License                          = Creative Commons Attribution-Non-Commercial-Share Alike 3.0
 Information                      = Cursors variables. ACTUALLY USELESS NOW, DO NOT EVEN TRY TO ENABLE THIS! IT WILL BE FIXED SOON

; --- ATTENTION ---

; --- ACTUALLY USELESS NOW ---

; --- DO NOT EVEN TRY TO ENABLE THIS ---

; --- YOUR PC WILL BURN ---

; --- YOUR PSYCHIC WILL BE COMPLETELY DESTROYED ---

; --- IN ADDITION WITH 86% CHANCE THE GRAVITY IN 200KM RADIUS MAY BE COLLAPSED WITH ALL THE ENSUING CONSEQUENCES ---

; --- E MIGHT BECOME MC3 ---

; --- YOU ARE WARNED ---

[Variables]
 Cursor_Slider_X                  = "SizeWE.ani"
 Cursor_Slider_Y                  = "SizeNS.ani"
 Cursor_Slider_XY                 = "SizeAll.ani"
 Hand                             = "Hand.ani"