[Metadata]
 Name                             = AuroraBar
 Version                          = 2.1.3b
 Author                           = deflore08 (deflore08@gmail.com) | https://www.deviantart.com/deflore08
 License                          = Creative Commons Attribution-Non-Commercial-Share Alike 3.0
 Information                      = Fonts
 
[Variables]

; --- MAIN FONTS

 FontColor                        = #Font_Color#
 Font_Size                        = 10
 Font_Size_Small                  = 7
 Faded_Font_Size_Small            = 7
 Font                             = AGENCY FB
 Bold_Font                        = AGENCY FB
 String_Style                     = Normal
 T_String_Style                   = Normal

; --- TIME FONTS

 Time_Font_Main                   = BRETTON
 Time_Font_Size_Day               = 15
 Time_Font_Size_Cday              = 15
 Time_Font_Color_Main             = #Font_Color#
 Time_Font_Color_Hours            = #Font_Color#
 Time_Font_Color_Mins             = #Font_Color#
 Time_Font_Size_Main              = 20
 Time_Font_Size_Hours             = 40
 Time_Font_Size_Mins              = 24
 Time_Font_Size_Secs              = 14
 Time_Font_Size_Date              = 15
 Time_Font_Size_Year              = 15

; --- DEPRECATED

; Time_Font_Hours                  =
; Time_Font_Mins                   =
; Time_Font_Secs                   =
; Time_Font_Date                   =
; Time_Font_Year                   =
; Time_Font_Month                  =
; Time_Font_Day                    =
; Time_Font_Cday                   =
; Time_Font_Size_Month             =
; Time_Font_Color_Secs             =
; Time_Font_Color_Date             =
; Time_Font_Color_Year             =
; Time_Font_Color_Month            =
; Time_Font_Color_Day              =
; Time_Font_Color_Cday             =

; Weather_Font_Size_Temp           = 15
; Weather_Font_Size_Condition      = 15
