[Metadata]
 Name                             = AuroraBar
 Version                          = 2.1.5b
 Author                           = deflore08 (deflore08@daid-art.online) | https://www.deviantart.com/deflore08
 License                          = Creative Commons Attribution-Non-Commercial-Share Alike 3.0
 Information                      = List of group for massive operations. It's useless for end user, i use this to comfortable work with IDE.

[Variables]

; --- GENERAL GROUPS

 main                                = main
 shapes                              = shapes
 texts                               = texts
 bars                                = bars
 values                              = values
 sensors                             = sensors
 histograms                          = histograms

; --- COMMON INFO

 clock_info                          = clock_info
 threads                             = threads

; --- CPU

 cpu                                 = cpu
 cpu_cores                           = cpu_cores
 cpu_top                             = cpu_top
 cpu_info                            = cpu_info
 cpu_graph                           = cpu_graph
 cpu_texts                           = cpu_texts
 cpu_values                          = cpu_values
 cpu_sensors                         = cpu_sensors
 cpu_histograms                      = cpu_histograms

; --- GPU

 gpu                                 = gpu
 gpu_graph                           = gpu_graph
 gpu_top                             = gpu_top
 gpu_info                            = gpu_info
 gpu_texts                           = gpu_texts
 gpu_values                          = gpu_values
 gpu_sensors                         = gpu_sensors
 gpu_bars                            = gpu_bars
 gpu_histograms                      = gpu_histograms

; --- MEMORY

 vram                                = vram
 vram_top                            = vram_top
 vram_sensors                        = vram_sensors
 vram_texts                          = vram_texts
 vram_values                         = vram_values
 vram_bars                           = vram_bars
 ram                                 = ram
 ram_sensors                         = ram_sensors
 ram_top                             = ram_top
 ram_texts                           = ram_texts
 ram_values                          = ram_values
 ram_bars                            = ram_bars

; --- DRIVES

 drives                              = drives
 drives_left_side                    = drives_left_side
 drives_sensors                      = drives_sensors
 drives_texts                        = drives_texts
 drives_values                       = drives_values
 drives_bars                         = drives_bars
 io_read_top                         = io_read_top
 io_write_top                        = io_write_top


; --- NET

 net                                 = net
 net_sensors                         = net_sensors
 net_texts                           = net_texts
 net_values                          = net_values
 net_bars                            = net_bars

; --- SHAPES

 bg_wings_shapes                     = bg_wings_shapes
 io_read_top_shapes                  = io_read_top_shapes
 io_write_top_shapes                 = io_write_top_shapes
 ram_top_shapes                      = ram_top_shapes
 vram_top_shapes                     = vram_top_shapes
 gpu_top_shapes                      = gpu_top_shapes
 gpu_info_shapes                     = gpu_info_shapes
 cpu_info_shapes                     = cpu_info_shapes
 cpu_top_shapes                      = cpu_top_shapes
 threads_shapes                      = threads_shapes
 clock_info_shapes                   = clock_info_shapes
 power_limit_shapes                  = power_limit_shapes
 throttling_shapes                   = throttling_shapes

; --- UNCATEGORIZED

 app_volume_controls_static          = app_volume_controls_static
 app_volume_controls_dynamic         = app_volume_controls_dynamic
 app_volume_controls_static_sensors  = app_volume_controls_static_sensors
 app_volume_controls_dynamic_sensors = app_volume_controls_dynamic_sensors
 app_volume_controls_static_texts    = app_volume_controls_static_texts
 app_volume_controls_static_bars     = app_volume_controls_static_bars
 clock_and_date                      = clock_and_date
 volume_control                      = volume_control
 player_controls                     = player_controls
 calculator                          = calculator
 bluetooth                           = bluetooth

; --- LOGS

 logs                                = logs
 logs_sensors                        = logs_sensors
 logs_texts                          = logs_texts
 logs_values                         = logs_values
 logs_bottom                         = logs_bottom
 logs_bottom_shapes                  = logs_bottom_shapes
 logs_top                            = logs_top
 logs_top_shapes                     = logs_top_shapes

; --- CONFIG

 menu_measures                       = menu_measures
 config                              = config
 settings_menu                       = settings_menu
 settings_main                       = settings_main
 settings_color                      = settings_color
 settings_hardware                   = settings_hardware
 settings_behaviour                  = settings_behaviour
 pallete                             = pallete

; --- LIMITERS

 limiters                            = limiters
 limiters_sensors                    = limiters_sensors
 throttling                          = throttling
 power_limit                         = power_limit
 limiters_texts                      = limiters_texts
 limiters_values                     = limiters_values

; --- MEASURES

 handlers                            = handlers
 sounds_wings_bottom                 = sounds_wings_bottom
 sounds_wings_top                    = sounds_wings_top
 app_volume_static_process           = app_volume_static_process
 sizer_bottom                        = sizer_bottom
 sizer_top                           = sizer_top
 terminators                         = terminators

; --- TIMER

 countdown                           = countdown
 timer                               = timer

; --- STOPWATCH

 stopwatch                           = stopwatch
 stopwatch_sensors                   = stopwatch_sensors
 stopwatch_texts                     = stopwatch_texts
 stopwatch_values                    = stopwatch_values

; --- UPTIME

 uptime                              = uptime
 uptime_sensors                      = uptime_sensors
 uptime_texts                        = uptime_texts
 uptime_values                       = uptime_values

; --- POWER PLAN

 power_plan                          = power_plan
 power_plan_sensors                  = power_plan_sensors
 power_plan_shapes                   = power_plan_shapes

; --- NOTES

 notes                               = notes
 notes_sensors                       = notes_sensors
 notes_texts                         = notes_texts
 notes_values                        = notes_values

; --- DEBUG

 debug                               = debug

 updater                             = updater