[Metadata]
 Name                             = AuroraBar
 Version                          = 2.1.5b
 Author                           = deflore08 (deflore08@daid-art.online) | https://www.deviantart.com/deflore08
 License                          = Creative Commons Attribution-Non-Commercial-Share Alike 3.0
 Information                      = Service file for updates, for control which variables added/deleted

; --- BUILD 2161 ---

; - NEW VARS

; Cursors_Set

; - DELETED VARS

; Sys_Volume_Down
; Sys_Volume_Up
; Player_Volume_Down
; Player_Volume_Up
; Position_Forward
; Position_Backward