[Metadata]
 Name                             = AuroraBar
 Version                          = 2.1.6b
 Author                           = deflore08 (deflore08@daid-art.online) | https://www.deviantart.com/deflore08
 License                          = Creative Commons Attribution-Non-Commercial-Share Alike 4.0
 Information                      = Service file for updates, for control which variables added/deleted

; --- BUILD 2161 ---

; - NEW VARS

; Cursors_Set

; - DELETED VARS

; Sys_Volume_Down                 = ADDED
; Sys_Volume_Up                   = ADDED
; Player_Volume_Down              = ADDED
; Player_Volume_Up                = ADDED
; Position_Forward                = ADDED
; Position_Backward               = ADDED